"""Builds PyTrainer.exe (Windows/Linux) and prepares the handout folder.

    .venv\\Scripts\\python.exe tools\\build_exe.py

What it does:
1. checks that PyInstaller is installed (and hints how to install it);
2. draws the icons if missing (assets/icon.png, assets/icon.ico);
3. builds one file `dist/PyTrainer.exe` from `pytrainer.spec`;
4. puts README, LICENSE and a short manual next to it — so whoever
   downloaded the archive has nothing left to build;
5. asks the built .exe to run code and show a verdict — if it cannot,
   the build counts as failed (`--no-check` switches this check off).

With `--install` the same .exe is also copied to the project root —
where the progress already lives. For yourself that is the handiest option:
code launches and .exe launches see one database. `tools/make_shortcut.py`
makes a shortcut to that .exe.

The app creates the user progress itself — next to the .exe
(see trainer/paths.py).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
EXE_NAME = "PyTrainer.exe" if sys.platform == "win32" else "PyTrainer"

HOWTO = """PyTrainer — тренажер Python
================================

1. Запусти PyTrainer{ext} (подвійний клік).
2. Прогрес (pytrainer.db) лежить у службовій теці системи, а не в цій:
   Windows — %LOCALAPPDATA%\PyTrainer, інші системи —
   ~/.local/share/PyTrainer. Відкрити її можна з меню «Файл → Відкрити
   теку з даними», а поруч із .exe лишаються progress.json,
   Python-Roadmap.md і pytrainer.ini (налаштування).
3. Щоб перенести прогрес на інший комп'ютер, скопіюй теку даних цілком,
   скористайся «Файл → Експортувати прогрес» або запусти з прапорцем
   --data-dir ТЕКА — тоді все ляже в одну теку, яку можна носити з собою.

Інтернет не потрібен, права адміністратора — теж.
""".format(ext=".exe" if sys.platform == "win32" else "")


def ensure_icons() -> None:
    png = ROOT / "assets" / "icon.png"
    ico = ROOT / "assets" / "icon.ico"
    if png.exists() and ico.exists():
        return
    print("Іконок немає — малюю…")
    subprocess.run([sys.executable, str(ROOT / "tools" / "make_icon.py")], check=True)


def check_self_test(exe: Path) -> bool:
    """Asks the .exe to run code and show a verdict — the build's main check.

    The window opens even when code execution inside the built .exe is broken:
    that is exactly what happened once, when `sys.executable` inside the
    `.exe` is the trainer itself. So the build checks itself not for "does
    the window draw" but for "does the verdict arrive" (see
    `trainer/core/selfcheck.py`).
    """
    report = exe.parent / "selftest.json"
    print()
    print("Перевіряю, що .exe виконує код і перевірки…")
    result = subprocess.run([str(exe), "--self-test", str(report)], check=False)

    text = ""
    try:
        text = report.read_text(encoding="utf-8")
        steps = json.loads(text).get("steps", [])
    except (OSError, ValueError):
        steps = []
    for step in steps:
        mark = "ок" if step.get("ok") else "ПОМИЛКА"
        print(f"  [{mark}] {step.get('name')} — {step.get('detail')}")
    # An empty or unreadable report is not "all good" but "nothing was
    # actually checked": that is why both the exit code and the steps matter.
    return result.returncode == 0 and bool(steps) and all(step.get("ok") for step in steps)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Зібрати PyTrainer.exe")
    parser.add_argument(
        "--install", action="store_true",
        help="покласти .exe поруч із проєктом (туди, де лежить прогрес)",
    )
    parser.add_argument(
        "--no-check", action="store_true",
        help="не перевіряти зібраний .exe самоперевіркою (вона запускає його 7 разів)",
    )
    args = parser.parse_args(argv)

    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print(
            "PyInstaller не встановлено.\n"
            "Постав його так:\n"
            f"    {sys.executable} -m pip install -r requirements-dev.txt"
        )
        return 1

    ensure_icons()

    from datetime import datetime
    sys.path.insert(0, str(ROOT))
    from trainer import __version__
    (ROOT / "trainer" / "_build.py").write_text(
        f'"""Build date — generated by tools/build_exe.py, do not touch by hand."""\n'
        f'BUILD_DATE = "{datetime.now().strftime("%Y-%m-%d")}"\n'
        f'BUILD_VERSION = "{__version__}"\n',
        encoding="utf-8",
    )

    command = [
        sys.executable,
        "-m",
        "PyInstaller",
        str(ROOT / "pytrainer.spec"),
        "--noconfirm",
        "--clean",
        "--workpath",
        str(ROOT / "build"),
        "--distpath",
        str(DIST),
    ]
    print("Збираю:", " ".join(command[2:]))
    result = subprocess.run(command, cwd=ROOT)
    if result.returncode != 0:
        return result.returncode

    built = DIST / EXE_NAME
    if not built.exists():
        print(f"Збірка завершилась, але {built} не знайдено")
        return 1

    for name in ("README.md", "LICENSE"):
        source = ROOT / name
        if source.exists():
            shutil.copy2(source, DIST / name)
    (DIST / ("ЯК_ЗАПУСКАТИ.txt" if sys.platform == "win32" else "HOW_TO_RUN.txt")).write_text(
        HOWTO, encoding="utf-8"
    )

    if not args.no_check and not check_self_test(built):
        print()
        print("Самоперевірка не пройшла: .exe зібрано, але код у ньому не виконується.")
        print("Вікно при цьому відкривається — тому й перевіряємо вердикт, а не вікно.")
        return 1

    print()
    print(f"Готово: {built} ({built.stat().st_size / 1_048_576:.1f} МБ)")
    print(f"Роздавати можна всю теку: {DIST}")

    if args.install:
        installed = ROOT / EXE_NAME
        shutil.copy2(built, installed)
        print()
        print(f"Встановлено поруч із проєктом: {installed}")
        print("База знайома та сама, що й у запуску з коду — прогрес не подвоюється.")
        sys.path.insert(0, str(ROOT))
        from trainer.paths import data_folder      # noqa: PLC0415

        print(f"Дані (база, копії, замок): {data_folder()}")
        print(f"Ярлик на робочий стіл: {sys.executable} tools/make_shortcut.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
